### ISSUE TITLE
private property 테스트에 관한 질문

### ISSUE THREAD

**Issue by cozzin** [devxoul/Testables#1]
테스트를 할때 간혹 private property를 테스트하고 싶다는 생각이 들 때가 있어서 흥미로운 프로젝트라고 생각합니다. 그런데 조금 고민되는 부분이 있어서 의견듣고 싶어서 이슈에 남깁니다.

객체의 행위를 기반으로 테스트 해야, 내부의 구현이 변경 되더라도 안정적인 테스트 코드를 가져갈 수 있다고 알고 있습니다.(행위 기반 테스트) 그런 측면으로 보면 객체 내부의 private한 값을 테스트하는 것은, 행위가 아니라 내부의 구현에 의존하게 됩니다. 이런점을 감안하더라도 private property를 테스트하면 얻을 수 있는 장점은 어떤게 있을까요?

**Comment by devxoul** [comment]
Hi, thanks for asking. You've got a good point. As you mentioned unit tests should test a behavior, not an implementation. But in the real world, especially for GUI, it's not always possible to test the behavior properly.

This simple code describes how difficult behavior testing is:

```swift
class ProfileViewController {
  var username: String? {
    didSet {
      self.usernameLabel.text = self.username // how would you test this?
    }
  }
  private let usernameLabel = UILabel()
}
```

Well, of course you can traverse the entire view hierarchy and find a text element that includes the username string. But it would be better just assert `usernameLabel.text` directly.

**Comment by cozzin** [comment]
Thank you for your comment. 😄 Now I understand. Yeah it's hard to test GUI component, because most of the GUI component is private.
